[build]
  command = "npm run build"
  output = "dist"

[dev]
  command = "npm run dev"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[routes]]
  src = "/(.*)"
  dest = "/index.html"
